[tool.black]
include = '\.pyi?$'
extend-exclude = '''
(
    .venv
    | __
    | /\.
    | tests
)
'''
line_length = 79
skip-string-normalization = true

[tool.isort]
profile = "black"
src_paths = ["."]
extend_skip = ["tests"]
line_length = 79

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
exclude = ['tests', '.venv']

[tool.pytest.ini_options]
norecursedirs = [".venv/*"]
addopts = "-vv -p no:cacheprovider -p no:warnings --show-capture=no"
testpaths = ["tests/"]
python_files = ["test_*.py"]
